name: 01-building-blocks
on: push
on: workflow_dispatch

jobs:
   echo-hello:
      runs-on: ubuntu-latest
      steps:
         -run: echo "Hello, World!"
   echo-goodbye:
      runs-on: ubuntu-latest
      steps:
         -run: echo "I will fail"
      steps:
         -run: echo "Goodbye"
